In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#import .crowd_nav/
import numpy as np
#import socialforce
import torch
import random

In [3]:
from crowd_sim.envs.policy.socialforce import *

In [7]:
np.set_printoptions(precision=2)

In [3]:
static_human_num = {0: 0.05, 1: 0.2, 2: 0.2, 3: 0.3, 4: 0.1, 5: 0.15}
dynamic_human_num = {1: 0.3, 2: 0.3, 3: 0.2, 4: 0.1, 5: 0.1}
static = True if np.random.random() < 0.2 else False
static

False

In [3]:
prob = np.random.random()
prob

0.6923801732524272

In [ ]:
dynamic_human_num.items()

In [9]:
static_human_num.items()

dict_items([(0, 0.05), (1, 0.2), (2, 0.2), (3, 0.3), (4, 0.1), (5, 0.15)])

In [12]:
static_human_num.items() if static else dynamic_human_num.items()

dict_items([(1, 0.3), (2, 0.3), (3, 0.2), (4, 0.1), (5, 0.1)])

In [13]:
for key, value in sorted(static_human_num.items() if static else dynamic_human_num.items()):
    print("prob:", prob)
    print("value:", value)
    print("prob - value:", prob - value)
    if prob - value <= 0:
        human_num = key
        break
    else:
        prob -= value
human_num

prob: 0.004089819458059085
value: 0.3
prob - value: -0.2959101805419409


NameError: name 'self' is not defined

In [17]:
np.random.normal(1.34, 0.26, size=(2))

array([4.834088  , 4.08984426])

In [18]:
np.iinfo(np.uint32).max - 2000

4294965295

In [20]:
'orca' in ('orca', 'sf', 'multi')

True

In [28]:
from crowd_sim.envs.utils.utils import get_random_policy

get_random_policy()

'sf'

In [33]:
a = [1]

if a:
    print("heyo")

heyo


In [87]:
#(  x,   y, v_x, v_y, [a_x, a_y], [d_x, d_y], [tau])
init_state = np.array([
   #(  px,   py,  vx,   vy,   gx,   gy, [tau])
    [ 1.0,  6.0, 0.4,  1.0,  3.0, 10.0, 0.5],
    [ 3.0,  2.0, 0.9, -1.0, -0.3, -5.0, 0.5],
    [ 4.0,  6.0, 1.2, -1.0,  0.0,  0.0, 0.5],
])

#generator = Simulator(initial_state)#, tau=np.array([0.5, 0.3]))# 1) # (initial_state)

#generator


# v0 = torch.tensor(1.2, requires_grad=True)
# sigma_v = torch.tensor(0.1, requires_grad=True)
# V = socialforce.PedPedPotential(0.4, v0, sigma_v)

# print('loop')
# s = socialforce.Simulator(initial_state, None, V)

In [97]:
r = init_state[:, 0:2]
print("r:", r.shape, "\n", r, "\n")

r_a = np.expand_dims(r, 1)
print("\nr_a:", r_a.shape, "\n", r_a, "\n")

r_b = np.expand_dims(r, 0)
print("\nr_b:", r_b.shape, "\n", r_b, "\n")

r_ab = r_a - r_b
print("\nr_a - r_b:", r_ab.shape, "\n", r_ab, "\n")

r_ab_norm = np.linalg.norm(r_ab, axis=2)
#print("\nr_ab_norm:", r_ab_norm.shape, "\n", r_ab_norm, "\n")


r_ab_norm_rep = np.repeat(r_ab_norm[:, :, np.newaxis], 2, axis=2)
#print("\nr_ab_norm_rep:", r_ab_norm_rep.shape, "\n", r_ab_norm_rep, "\n")

#r_ab_unit = r_ab / r_ab_norm
r_ab_unit = np.divide(r_ab, r_ab_norm_rep, out=np.zeros_like(r_ab), where=r_ab_norm_rep!=0)
#print("\nr_ab_unit:", r_ab_unit.shape, "\n", r_ab_unit, "\n")


dist_minus_radius = r_ab_norm_rep - 1
#print("\ndist_minus_radius:", dist_minus_radius.shape, "\n", dist_minus_radius, "\n")

new_norm = np.where(dist_minus_radius < 0, 0, dist_minus_radius)
#print("\nnew_norm:", new_norm.shape, "\n", new_norm, "\n")


r_ab_new = r_ab_unit * new_norm
print("\nr_ab_new:", r_ab_new.shape, "\n", r_ab_new, "\n")

r: (3, 2) 
 [[1. 6.]
 [3. 2.]
 [4. 6.]] 


r_a: (3, 1, 2) 
 [[[1. 6.]]

 [[3. 2.]]

 [[4. 6.]]] 


r_b: (1, 3, 2) 
 [[[1. 6.]
  [3. 2.]
  [4. 6.]]] 


r_a - r_b: (3, 3, 2) 
 [[[ 0.  0.]
  [-2.  4.]
  [-3.  0.]]

 [[ 2. -4.]
  [ 0.  0.]
  [-1. -4.]]

 [[ 3.  0.]
  [ 1.  4.]
  [ 0.  0.]]] 


r_ab_new: (3, 3, 2) 
 [[[ 0.    0.  ]
  [-1.55  3.11]
  [-2.    0.  ]]

 [[ 1.55 -3.11]
  [ 0.    0.  ]
  [-0.76 -3.03]]

 [[ 2.    0.  ]
  [ 0.76  3.03]
  [ 0.    0.  ]]] 



In [100]:
a = np.array([-2,4])
print(np.linalg.norm(a))
a_unit = a / np.linalg.norm(a)
norm_min_1 = np.linalg.norm(a) - 1
a_unit * norm_min_1

#np.linalg.norm([-1.55,  3.11])

4.47213595499958


array([-1.55,  3.11])

In [47]:
init_state[:,:6] = np.zeros((3,6))
init_state

array([[0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5]])

In [53]:
(3,6) == init_state.shape - np.array((0,1))

array([ True,  True])

In [42]:
statecpy = np.copy(init_state)

print(np.linalg.norm((init_state[:,0:2] - init_state[:,4:6]), axis=1) <= 0.1)
print(np.nonzero(np.linalg.norm(init_state[:,0:2] - init_state[:,4:6], axis=1) <= 0.1 ))

statecpy[np.nonzero(np.linalg.norm(init_state[:,0:2] - init_state[:,4:6], axis=1) <= 0.1 ), 2:4] = 0
statecpy

[False False False]
(array([], dtype=int64),)


array([[ 0. ,  0. ,  0.4,  1. ,  3. , 10. ,  0.5],
       [-0.3, -4.8,  0.9, -1. , -0.3, -5. ,  0.5],
       [ 7. , -5. ,  1.2, -1. ,  0. ,  0. ,  0.5]], dtype=float32)

In [18]:
np.sqrt(109)

10.44030650891055

In [9]:
generator.max_speeds

array([1.3, 1.3], dtype=float32)

In [10]:
*initial_state

SyntaxError: can't use starred expression here (<ipython-input-10-526db5137f0b>, line 4)

In [14]:
np.random.rand(3)

array([0.77689711, 0.59666118, 0.70730649])

In [1]:
import sys
sys.version

'3.6.15 (default, Jan 15 2022, 19:47:13) \n[GCC 9.3.0]'